In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("./datasets/train.csv", usecols=['Age', 'Survived', 'Fare'])

In [4]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [5]:
df.dropna(inplace= True)

In [6]:
df.shape

(714, 3)

In [7]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

# Bining/ Discretization
    - Consist of 3 types: Uniform(Bins having same width), quantile(bins having same frequency) and kmeans bining

In [8]:
x= df.iloc[:, [1, 2]]
y= df['Survived']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2)

In [10]:
from sklearn.preprocessing import KBinsDiscretizer 
from sklearn.compose import ColumnTransformer  #for binning

clf= ColumnTransformer(
    transformers=[
        ('clf1', KBinsDiscretizer(n_bins= 10, encode= 'ordinal', strategy= 'uniform'), ['Age']) ,  #n_bins= no. of bins/interval, encde= ordinal or one hot and strategy= uniform, discrete or kmeans
        ('clf2', KBinsDiscretizer(n_bins= 15, encode= "ordinal", strategy='quantile'), ['Fare'])
    ], remainder= 'passthrough', verbose_feature_names_out= False
)

In [11]:
clf.fit(x_train)

c:\Users\Yunish\miniconda3\envs\myenv\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

ColumnTransformer(remainder='passthrough',
                  transformers=[('clf1',
                                 KBinsDiscretizer(encode='ordinal', n_bins=10,
                                                  strategy='uniform'),
                                 ['Age']),
                                ('clf2',
                                 KBinsDiscretizer(encode='ordinal', n_bins=15),
                                 ['Fare'])],
                  verbose_feature_names_out=False)

In [12]:
x_train_clf= clf.transform(x_train)
x_test_clf= clf.transform(x_test)

In [13]:
clf.set_output(transform= "pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('clf1',
                                 KBinsDiscretizer(encode='ordinal', n_bins=10,
                                                  strategy='uniform'),
                                 ['Age']),
                                ('clf2',
                                 KBinsDiscretizer(encode='ordinal', n_bins=15),
                                 ['Fare'])],
                  verbose_feature_names_out=False)

In [14]:
x_train_clf   #here each numerical value is replaced by its  inverval and ordinal encpding is done in that onterval

array([[ 3., 11.],
       [ 7.,  0.],
       [ 4., 14.],
       ...,
       [ 1., 12.],
       [ 3., 12.],
       [ 4.,  4.]], shape=(571, 2))

In [15]:
clf.get_feature_names_out()

array(['Age', 'Fare'], dtype=object)

# Binarization
- Used in special cases only
- It converts a column into binary value depending on the threshold
- it copy = true then it will create new column. If copy is false then it will make changes in same column

In [16]:
from sklearn.preprocessing import Binarizer
 
df= pd.read_csv("./datasets/train.csv")

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
df.dropna(inplace= True)

In [19]:
df= df.iloc[:, [ 1, 6, 7]]

In [20]:
df.head()

    Survived  SibSp  Parch
1          1      1      0
3          1      1      0
6          0      0      0
10         1      1      1
11         1      0      0

In [21]:
df['Siblings']= df['SibSp'] + df['Parch']

In [22]:
df.head()

    Survived  SibSp  Parch  Siblings
1          1      1      0         1
3          1      1      0         1
6          0      0      0         0
10         1      1      1         2
11         1      0      0         0

In [23]:
df.drop(columns= ['SibSp', 'Parch'], inplace= True)

In [24]:
df.head()

    Survived  Siblings
1          1         1
3          1         1
6          0         0
10         1         2
11         1         0

In [25]:
# Appllying on Siblings if 0 then 0 ie NO siblings, If more than 0 than siblings present= 1
bnz= Binarizer(threshold= 0, copy= False)

In [26]:
df_new= bnz.fit_transform(df)

In [27]:
pd.DataFrame(df_new, columns= bnz.get_feature_names_out()).head()

   Survived  Siblings
0         1         1
1         1         1
2         0         0
3         1         1
4         1         0